### PR TITLE
feat: add profiling support

### PR DESCRIPTION
**Pull request by theSuess**

### CODE REVIEW

**Review by roobre — COMMENTED** [review]
I'd like to know a bit more about the use case for this. Is this intended to demonstrate something, or purely for development purposes?

If it's the former, we should probably think about how this will interact with microservices deployment in k8s. As it stands now, I think the `/debug` endpoint defined here will only be reachable for one service, the frontend/gateway. I suspect this service will be the least interesting in terms of profiling.

**Comment by theSuess** [comment]
It's intended to demo pyroscope. The endpoint should be available on all microservices and will be scraped by the agent which sends the data to the backend (similar to prometheus).

**Comment by roobre** [comment]
Got it, for some reason I was thinking about this needing to be user-reachable. Looking awesome then!

**Review by roobre — APPROVED** [review]

**Comment by dgzlopes** [comment]
Would it be better to use the Push approach? 

That way, it can be configured easily, even when running it as a single container to push the profiles to the Cloud.

**Comment by theSuess** [comment]
IMHO the pull based approach is easier to grasp if you're already coming from prometheus and makes it easier to have this as an optional feature. I'll add an agent config file soon, which will streamline shipping all data we gather to the cloud

**Pull request merged**
